from distutils.core import setup
setup(name='Langcard',
      version='0.1',
      description='Custom languages cards',
      author='Andres Estevez-Costas',
      author_email='aecostas@gmail.com',
      maintainer='Andres Estevez-Costas',
      maintainer_mail='aecostas@gmail.com',
      url='',
      download_url='',
      platforms='',
      license='GPLv3',
      packages=['langcard'],
      package_dir={'langcard': 'src/langcard'},
      package_data={'langcard': ['js/*.js', 'db/*', 'html/*', 'css/*.css']},
      classifiers=[
          'Development Status :: 4 - Beta',
          'Environment :: Desktop',
          'Intended Audience :: End Users/Desktop',
          'License :: GPL v3',
          'Operating System :: GNU/Linux',
          'Programming Language :: Python',
          'Topic :: Office/Education',
          ],

      )
